
#ifndef USER_SETTINGS_H
#define USER_SETTINGS_H

#define WOLFENGINE_DEBUG
#define WE_USE_HASH
#define WE_HAVE_SHA384
#define WE_HAVE_SHA512
#define WE_HAVE_SHA1
#define WE_HAVE_SHA224
#define WE_HAVE_SHA256
#define WE_HAVE_SHA3_224
#define WE_HAVE_SHA3_256
#define WE_HAVE_SHA3_384
#define WE_HAVE_SHA3_512
#define WE_HAVE_DES3CBC
#define WE_HAVE_AESECB
#define WE_HAVE_AESCBC
#define WE_HAVE_AESCTR
#define WE_HAVE_AESGCM
#define WE_HAVE_AESCCM
#define WE_HAVE_RSA
#define WE_HAVE_ECC
#define WE_HAVE_EVP_PKEY
#define WE_HAVE_EC_KEY
#define WE_HAVE_ECDSA
#define WE_HAVE_ECDH
#define WE_HAVE_ECKEYGEN
#define WE_HAVE_EC_P256
#define WE_HAVE_EC_P384
#define WE_HAVE_DIGEST

#endif
